package com.bizwiz.post.Enums;

public enum Category {
    TECNOLOGIA,
    FINANZAS,
    MARKETING,
    VENTAS,
    RECURSOS_HUMANOS,
    OPERACIONES,
    LEGAL,
    ESTRATEGIA,
    INVERSION,
    NETWORKING,
    PRODUCTIVIDAD,
    LIDERAZGO,
    DESARROLLO_PERSONAL,
    INNOVACION,
    SOSTENIBILIDAD,
    ECOMMERCE,
    SOCIAL_MEDIA,
    ANALITICA,
    SERVICIO_AL_CLIENTE,
    LOGISTICA
}
