server:
  port: 9002

spring:
  application:
    name: post
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/post?serverTimezone=UTC
    username: root
    password: root

eureka:
  client:
    service-url.defaultZone: http://localhost:8761/eureka/