server:
  port: 443

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
    routes:
      - id: post-service-route
        uri: lb://post
        predicates:
          - Path=/post/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




